# Internal Clustering Job Configuration
# This file contains configuration for the internal clustering job

# Preprocessing parameters
preprocessing:
  # Feature selection
  feature_selection:
    min_variance: 0.01
    max_correlation: 0.95

  # Outlier detection
  outlier_detection:
    method: "IQR" # Options: IQR, Z-score, Isolation Forest
    threshold: 1.5

  # Scaling method
  scaling:
    method: "standard" # Options: standard, minmax, robust
    with_mean: true
    with_std: true

# Clustering parameters
clustering:
  # Algorithm choice
  algorithm: "kmeans" # Options: kmeans, dbscan, hierarchical, gmm

  # Parameters for KMeans
  kmeans:
    n_clusters: 5
    random_state: 42
    n_init: 10
    max_iter: 300

  # Parameters for DBSCAN (if used)
  dbscan:
    eps: 0.5
    min_samples: 5

  # Parameters for Hierarchical (if used)
  hierarchical:
    n_clusters: 5
    linkage: "ward"

  # Parameters for GMM (if used)
  gmm:
    n_components: 5
    covariance_type: "full"
    random_state: 42

# Evaluation parameters
evaluation:
  metrics:
    - "silhouette_score"
    - "davies_bouldin_score"
    - "calinski_harabasz_score"

  # Visualization
  visualize:
    method: "pca" # Options: pca, tsne, umap
    n_components: 2
    random_state: 42

# Output parameters
output:
  # Format for clustering results
  format: "parquet" # Options: parquet, csv, json
  include_metrics: true
  include_centroids: true
