# Clustering component configuration

# Available clustering algorithms
algorithms:
  kmeans:
    default_params:
      n_clusters: 3
      random_state: 42
      init: k-means++
      n_init: 10
      max_iter: 300
      tol: 1e-4

  dbscan:
    default_params:
      eps: 0.5
      min_samples: 5
      metric: euclidean
      algorithm: auto
      leaf_size: 30

  hierarchical:
    default_params:
      n_clusters: 3
      linkage: ward
      affinity: euclidean

# Evaluation metrics
evaluation:
  metrics:
    - silhouette_score
    - calinski_harabasz_score
    - davies_bouldin_score

  visualization:
    enabled: true
    max_dimensions: 2 # For 2D visualization
    dimension_reduction:
      method: pca # Options: pca, tsne, umap
      params:
        n_components: 2
