repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.5.3
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: debug-statements
      - id: check-merge-conflict

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: mypy
        language: system
        types: [python]
        args: [--ignore-missing-imports]
        exclude: ^tests/

      - id: pyright
        name: pyright
        entry: pyright
        language: system
        types: [python]
        args: []
        exclude: ^tests/

      - id: pytest
        name: pytest
        entry: pytest
        language: system
        pass_filenames: false
        always_run: true
        args: [tests/]
