version: "3.8"

services:
  clustering:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./configs:/app/configs
      - ./logs:/app/logs
      - ./outputs:/app/outputs
      - ./reports:/app/reports
      - ./cache:/app/cache
    command: configs/internal_preprocessing.yml

  mlflow:
    image: ghcr.io/mlflow/mlflow:v2.16.0
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlruns
    command: mlflow server --host 0.0.0.0 --port 5000 --backend-store-uri /mlruns
