version: "3.8"

# Named volumes for persistent data
volumes:
  app_data:
  app_logs:

services:
  # Main chatbot application
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: chatbot-assistant
    restart: unless-stopped
    ports:
      - "8501:8501"
    volumes:
      - app_data:/app/data
      - app_logs:/app/logs
      - ./.env:/app/.env:ro
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LOG_LEVEL=INFO
      - DB_PATH=:memory:
      - MEMORY_TYPE=summary
      - MEMORY_TOKEN_LIMIT=4000
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

networks:
  app_network:
    driver: bridge
