# EXAMPLE SECRETS FILE - Copy to .streamlit/secrets.toml and fill in your values
# IMPORTANT: Never commit your actual secrets.toml file to source control!

# Azure Key Vault configuration 
# These are the ONLY secrets you need to store in Streamlit Secrets
# The actual sensitive credentials will be stored in Azure Key Vault
[key_vault]
KEY_VAULT_ENABLED = true
KEY_VAULT_URL = "https://your-vault-name.vault.azure.net/"

# Choose one authentication method:
# 1. Managed Identity (when deployed to Azure with managed identity enabled)
USE_MANAGED_IDENTITY = false  # Set to true when using Azure managed identity

# 2. Service Principal (alternative to managed identity)
CLIENT_ID = "your-azure-client-id"  # Only needed if not using managed identity
CLIENT_SECRET = "your-azure-client-secret"  # Only needed if not using managed identity
TENANT_ID = "your-azure-tenant-id"  # Only needed if not using managed identity

# Optional: specify only certain secrets to fetch (for better performance or security)
# If empty, all secrets will be fetched from the vault
# SECRET_NAMES = ["OPENAI_API_KEY", "AZURE_OPENAI_KEY"] 

# Optional: cache settings to reduce API calls to Key Vault
CACHE_SECRETS = true  
SECRET_REFRESH_INTERVAL = 3600  # Seconds between secret refreshes (1 hour)

# Local development fallbacks
# These are only used during local development if Key Vault is not accessible
# In production, these values will be overridden by secrets from Key Vault
OPENAI_API_KEY = ""  # For local development only 