clustering:
  algorithm: kmeans
  n_clusters: 5
  random_state: 42
  min_cluster_size: 5

io:
  base_dir: outputs/dagster_storage
  format: parquet

validation:
  min_samples: 10
  required_columns:
    - store_id
    - sales
    - date

logging:
  level: INFO
  retention_days: 30
