clustering:
  algorithm: hdbscan
  min_cluster_size: 50
  cluster_selection_epsilon: 0.5

io:
  base_dir: s3://prod-data/processed
  format: parquet

validation:
  min_samples: 100 # Stricter validation for production

logging:
  level: WARNING # Less verbose logging for production
  retention_days: 90 # Longer retention for production logs

alerts:
  enabled: true
  channels:
    - slack
    - email
  recipients:
    - data-team@example.com
