alerts:
  enabled: true
  threshold: WARNING
logger:
  level: DEBUG
  sink: logs/dagster_dev.log

# Base paths configuration - can be overridden by environment variables
paths:
  base_data_dir: ${env:DATA_DIR,/workspaces/testing-dagster/data}
  internal_data_dir: ${env:INTERNAL_DATA_DIR,/workspaces/testing-dagster/data/internal}
  external_data_dir: ${env:EXTERNAL_DATA_DIR,/workspaces/testing-dagster/data/external}
  merging_data_dir: ${env:MERGING_DATA_DIR,/workspaces/testing-dagster/data/merging}

# Job configuration parameters
job_params:
  ### --- Feature engineering parameters --- ###
  ignore_features: ["STORE_NBR"]

  # Normalization settings
  normalize: true
  norm_method: "robust"

  # Imputation settings
  imputation_type: "simple"
  numeric_imputation: "mean"
  categorical_imputation: "mode"

  # Outlier detection
  outlier_detection: true
  outliers_method: "iforest"
  outlier_threshold: 0.05

  # Dimensionality reduction
  pca_active: true
  pca_method: "linear"
  pca_components: 0.8

  # Metadata generation
  feature_metadata_detail: "full"

  ### --- Model training parameters --- ###

  # Optimal cluster count parameters
  min_clusters: 2
  max_clusters: 10
  metrics: ["silhouette", "calinski_harabasz", "davies_bouldin"]

  # Model training parameters
  algorithm: "kmeans"

  # Random seed for reproducibility
  session_id: 42

# Data sources and destinations
readers:
  # Internal data sources
  ns_map:
    kind: "CSVReader"
    config:
      path: ${env:INTERNAL_DATA_DIR,/workspaces/testing-dagster/data/internal}/ns_map.csv
  ns_sales:
    kind: "CSVReader"
    config:
      path: ${env:INTERNAL_DATA_DIR,/workspaces/testing-dagster/data/internal}/ns_sales.csv
  sales_by_category:
    kind: "PickleReader"
    config:
      path: ${env:INTERNAL_DATA_DIR,/workspaces/testing-dagster/data/internal}/sales_by_category.pkl

  # External data sources
  external_placerai:
    kind: "CSVReader"
    config:
      path: ${env:EXTERNAL_DATA_DIR,/workspaces/testing-dagster/data/external}/placerai.csv
  external_data_source:
    kind: "PickleReader"
    config:
      path: ${env:EXTERNAL_DATA_DIR,/workspaces/testing-dagster/data/external}/processed_external_data.pkl

writers:
  # Internal data writers
  sales_by_category:
    kind: "PickleWriter"
    config:
      path: ${env:INTERNAL_DATA_DIR,/workspaces/testing-dagster/data/internal}/sales_by_category.pkl
  internal_clusters_output:
    kind: "SnowflakeWriter"
    config:
      table: DEV_CLUSTERING_DB.PROCESSED.INTERNAL_CLUSTERS
      database: DEV_CLUSTERING_DB
      schema: PROCESSED
  feature_engineering_output:
    kind: "PickleWriter"
    config:
      path: ${env:INTERNAL_DATA_DIR,/workspaces/testing-dagster/data/internal}/engineered_features.pkl
  model_output:
    kind: "PickleWriter"
    config:
      path: ${env:INTERNAL_DATA_DIR,/workspaces/testing-dagster/data/internal}/clustering_models.pkl
  cluster_assignments:
    kind: "PickleWriter"
    config:
      path: ${env:INTERNAL_DATA_DIR,/workspaces/testing-dagster/data/internal}/cluster_assignments.pkl

  # External data writers
  external_data_output:
    kind: "PickleWriter"
    config:
      path: ${env:EXTERNAL_DATA_DIR,/workspaces/testing-dagster/data/external}/processed_external_data.pkl
  external_model_output:
    kind: "PickleWriter"
    config:
      path: ${env:EXTERNAL_DATA_DIR,/workspaces/testing-dagster/data/external}/clustering_models.pkl
  external_cluster_assignments:
    kind: "PickleWriter"
    config:
      path: ${env:EXTERNAL_DATA_DIR,/workspaces/testing-dagster/data/external}/cluster_assignments.pkl
  merged_clusters_output:
    kind: "SnowflakeWriter"
    config:
      table: DEV_CLUSTERING_DB.PROCESSED.MERGED_CLUSTERS
      database: DEV_CLUSTERING_DB
      schema: PROCESSED
  merged_cluster_assignments:
    kind: "PickleWriter"
    config:
      path: ${env:MERGING_DATA_DIR,/workspaces/testing-dagster/data/merging}/merged_cluster_assignments.pkl
