alerts:
  enabled: true
  threshold: WARNING
logger:
  level: DEBUG
  sink: logs/dagster_dev.log

# Job configuration parameters
job_params:
  # ML parameters
  algorithm: "kmeans"
  normalize: true
  norm_method: "robust"
  pca_active: true
  pca_components: 0.8
  ignore_features: ["STORE_NBR"]

  # Feature engineering parameters
  imputation_type: "simple"
  numeric_imputation: "mean"
  categorical_imputation: "mode"
  outlier_detection: true
  outliers_method: "iforest"
  outlier_threshold: 0.05
  pca_method: "linear"
  feature_metadata_detail: "full"
  verbose: false

  # MLflow configuration
  mlflow_tracking_uri: "http://localhost:5000"
  mlflow_experiment_name: "clustering_pipeline"

  # KMeans parameters
  kmeans:
    n_clusters: 5
    random_state: 42
    n_init: 10
    max_iter: 300

  # Evaluation parameters
  evaluation:
    metrics: ["silhouette_score", "davies_bouldin_score"]
    format: "parquet"

# Data sources and destinations
readers:
  internal_ns_map:
    kind: "CSVReader"
    config:
      path: /Users/jason/Files/Practice/cvs-repo-dagster/data/internal/ns_map.csv
  internal_ns_sales:
    kind: "CSVReader"
    config:
      path: /Users/jason/Files/Practice/cvs-repo-dagster/data/internal/ns_sales.csv
  external_placerai:
    kind: "CSVReader"
    config:
      path: /Users/jason/Files/Practice/cvs-repo-dagster/data/external/placerai.csv
  output_sales:
    kind: "PickleReader"
    config:
      path: /Users/jason/Files/Practice/cvs-repo-dagster/data/internal/sales_by_category.pkl

writers:
  internal_sales_output:
    kind: "PickleWriter"
    config:
      path: /Users/jason/Files/Practice/cvs-repo-dagster/data/internal/sales_by_category.pkl
  internal_clusters_output:
    kind: "SnowflakeWriter"
    config:
      table: DEV_CLUSTERING_DB.PROCESSED.INTERNAL_CLUSTERS
      database: DEV_CLUSTERING_DB
      schema: PROCESSED
  external_data_output:
    kind: "PickleWriter"
    config:
      path: /Users/jason/Files/Practice/cvs-repo-dagster/data/external/external_data.pkl
  merged_clusters_output:
    kind: "SnowflakeWriter"
    config:
      table: DEV_CLUSTERING_DB.PROCESSED.MERGED_CLUSTERS
      database: DEV_CLUSTERING_DB
      schema: PROCESSED
  feature_engineering_output:
    kind: "PickleWriter"
    config:
      path: /Users/jason/Files/Practice/cvs-repo-dagster/data/internal/engineered_features.pkl
