# External Clustering Configuration

job:
  kind: external_clustering # Job type

  # Logger configuration
  logger_service:
    level: INFO
    format: "[{time:YYYY-MM-DD HH:mm:ss}] {level} | {message}"
    file: logs/external_clustering_{time:YYYY-MM-DD}.log

  # Alerts configuration
  alerts_service:
    enabled: true
    threshold: WARNING

  # Data source configuration
  source:
    type: azure_blob
    container: ${CONTAINER_NAME}
    path: external/preprocessed_data.parquet
    format: parquet

  # Clustering parameters
  params:
    algorithm: hierarchical
    n_clusters: 4
    linkage: ward
    random_state: 42

    # Feature importance
    feature_weights:
      market_size: 1.3
      competition_density: 1.5
      demographic_index: 1.2
      traffic_score: 1.0
      area_income: 0.9
      population_density: 1.1
      growth_potential: 1.4

    # Experiment tracking
    mlflow:
      enabled: true
      experiment_name: external_clustering
      tags:
        version: "1.0"
        env: "production"

  # Output configuration
  output:
    type: azure_blob
    container: ${CONTAINER_NAME}
    path: external/clustering_results.parquet
    format: parquet

    # Visualization outputs
    visualizations:
      enabled: true
      output_dir: outputs/external_clustering_visuals
