# External Preprocessing Configuration

job:
  kind: external_preprocessing # Job type

  # Logger configuration
  logger_service:
    level: INFO
    format: "[{time:YYYY-MM-DD HH:mm:ss}] {level} | {message}"
    file: logs/external_preprocessing_{time:YYYY-MM-DD}.log

  # Alerts configuration
  alerts_service:
    enabled: true
    threshold: WARNING

  # Data source configuration
  source:
    type: azure_blob
    container: ${CONTAINER_NAME}
    path: external/raw_data.csv

  # Preprocessing parameters
  params:
    features_to_include:
      - store_id
      - market_size
      - competition_density
      - demographic_index
      - traffic_score
      - area_income
      - population_density
      - growth_potential

    outlier_removal:
      method: zscore
      threshold: 3.0

    imputation:
      method: median

    scaling:
      method: minmax

  # Output configuration
  output:
    type: azure_blob
    container: ${CONTAINER_NAME}
    path: external/preprocessed_data.parquet
    format: parquet
