# Merge Internal and External Clusters Configuration

job:
  kind: merge_int_ext # Job type

  # Logger configuration
  logger_service:
    level: INFO
    format: "[{time:YYYY-MM-DD HH:mm:ss}] {level} | {message}"
    file: logs/merge_int_ext_{time:YYYY-MM-DD}.log

  # Alerts configuration
  alerts_service:
    enabled: true
    threshold: WARNING

  # Data source configuration
  sources:
    internal:
      type: azure_blob
      container: ${CONTAINER_NAME}
      path: internal/clustering_results.parquet
      format: parquet

    external:
      type: azure_blob
      container: ${CONTAINER_NAME}
      path: external/clustering_results.parquet
      format: parquet

  # Merging parameters
  params:
    internal_weight: 0.6
    external_weight: 0.4
    approach: ensemble

    # Final cluster count
    n_final_clusters: 7

    # Experiment tracking
    mlflow:
      enabled: true
      experiment_name: merged_clustering
      tags:
        version: "1.0"
        env: "production"

  # Output configuration
  output:
    type: azure_blob
    container: ${CONTAINER_NAME}
    path: merged/final_clusters.parquet
    format: parquet

    # Visualization outputs
    visualizations:
      enabled: true
      output_dir: outputs/merged_clusters_visuals

    # Report generation
    report:
      enabled: true
      template: templates/cluster_report_template.html
      output: reports/cluster_analysis_{time:YYYY-MM-DD}.html
