"""
Sphinx configuration file for generating API documentation.

This file configures Sphinx to generate API documentation from docstrings
across the codebase.
"""

import os
import sys
from datetime import datetime

# Add the project root directory to the Python path
sys.path.insert(0, os.path.abspath('..'))

# Project information
project = 'Data Chat Assistant'
copyright = f'{datetime.now().year}, Data Chat Team'
author = 'Data Chat Team'
version = '0.1.0'
release = '0.1.0'

# General configuration
extensions = [
    'sphinx.ext.autodoc',  # Automatically generate API documentation
    'sphinx.ext.viewcode',  # Add links to view source code
    'sphinx.ext.napoleon',  # Support for NumPy and Google style docstrings
    'sphinx.ext.intersphinx',  # Link to other project's documentation
    'sphinx.ext.coverage',  # Check documentation coverage
    'sphinx_rtd_theme',  # Use Read the Docs theme
]

# Napoleon settings for NumPy-style docstrings
napoleon_google_docstring = False
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = True
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = True
napoleon_use_admonition_for_notes = True
napoleon_use_admonition_for_references = True
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True
napoleon_preprocess_types = True
napoleon_type_aliases = None
napoleon_attr_annotations = True

# Document Python objects (functions, classes, etc)
autoclass_content = 'both'  # Include both class and __init__ docstrings
autodoc_member_order = 'bysource'
autodoc_typehints = 'description'
autodoc_typehints_format = 'short'

# Add any paths that contain templates here
templates_path = ['_templates']

# The suffix of source filenames
source_suffix = '.rst'

# The master toctree document
master_doc = 'index'

# The language for content autogenerated by Sphinx
language = 'en'

# List of patterns to exclude from source files
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use
pygments_style = 'sphinx'

# HTML options
html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']
html_title = f"{project} {version} Documentation"

# Intersphinx mapping to other projects
intersphinx_mapping = {
    'python': ('https://docs.python.org/3', None),
    'pandas': ('https://pandas.pydata.org/pandas-docs/stable', None),
    'numpy': ('https://numpy.org/doc/stable', None),
    'streamlit': ('https://docs.streamlit.io', None),
}

# Auto-generate API docs
autodoc_default_options = {
    'members': True,
    'undoc-members': True,
    'show-inheritance': True,
    'special-members': '__init__',
} 